# Generated by Django 2.2.7 on 2019-12-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(blank=True, db_column='X', null=True)),
                ('Longitude', models.FloatField(blank=True, db_column='Y', null=True)),
                ('Unique_Squirrel_ID', models.CharField(blank=True, db_column='Unique Squirrel ID', max_length=200, null=True)),
                ('Shift', models.TextField(blank=True, db_column='Shift', null=True)),
                ('date', models.IntegerField(blank=True, db_column='Date', null=True)),
                ('age', models.TextField(blank=True, db_column='Age', null=True)),
                ('primary_fur_color', models.TextField(blank=True, db_column='Primary Fur Color', null=True)),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
                ('specific_location', models.TextField(blank=True, db_column='Specific Location', null=True)),
                ('running', models.IntegerField(blank=True, db_column='Running', null=True)),
                ('chasing', models.IntegerField(blank=True, db_column='Chasing', null=True)),
                ('climbing', models.IntegerField(blank=True, db_column='Climbing', null=True)),
                ('eating', models.IntegerField(blank=True, db_column='Eating', null=True)),
                ('foraging', models.IntegerField(blank=True, db_column='Foraging', null=True)),
                ('other_activities', models.TextField(blank=True, db_column='Other Activities', null=True)),
                ('kuks', models.IntegerField(blank=True, db_column='Kuks', null=True)),
                ('quaas', models.IntegerField(blank=True, db_column='Quaas', null=True)),
                ('moans', models.IntegerField(blank=True, db_column='Moans', null=True)),
                ('tail_flags', models.IntegerField(blank=True, db_column='Tail flags', null=True)),
                ('tail_twitches', models.IntegerField(blank=True, db_column='Tail twitches', null=True)),
                ('approaches', models.IntegerField(blank=True, db_column='Approaches', null=True)),
                ('indifferent', models.IntegerField(blank=True, db_column='Indifferent', null=True)),
                ('runs_from', models.IntegerField(blank=True, db_column='Runs from', null=True)),
            ],
        ),
    ]
