# Generated by Django 2.2.7 on 2019-11-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(help_text='Birth date')),
                ('species', models.CharField(help_text='species of animal', max_length=100)),
                ('name', models.CharField(help_text='name of animal', max_length=100)),
                ('sex', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHERS')], default='other', help_text='sex of pet', max_length=16)),
            ],
        ),
    ]
